[main]
# include=~/.config/fuzzel/colors.ini
include=~/.config/fuzzel/font.ini
include=~/.config/fuzzel/themes/noctalia

dpi-aware=no

# Layout
anchor=center
width=45
lines=8
use-bold=no

# Spacing
horizontal-pad=28
vertical-pad=20
inner-pad=8
letter-spacing=0
line-height=28

# Prompt
prompt="❯ "
placeholder=
match-counter=no

# Icons
icons-enabled=yes
image-size-ratio=0.5

# Behavior
match-mode=fzf
fields=filename,name,generic
layer=overlay

[border]
width=0
radius=0
selection-radius=0
