exec-once=qs -c noctalia-shell

# Screensharing, see: https://gist.github.com/brunoanc/2dea6ddf6974ba4e5d26c3139ffb7580
exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
