# Key Bindings

# Local docs:
# $HOME/external-repos/mango/docs/bindings/keys.md

# key name refer to `xev` or `wev` command output,
# mod keys name: super,ctrl,alt,shift,none

# reload config
bind=super,r,reload_config

# menu and terminal
bind=super,p,spawn,fuzzel --list-executables-in-path
bind=super,q,spawn,kitty

# browser
bind=super,b,spawn,qutebrowser

bind=super+shift,s,spawn,hyprshot -m region --clipboard-only
bind=super+CONTROL+shift,s,spawn,hyprshot -m output -m active --clipboard-only

# exit
bind=super,m,quit
bind=super+shift,c,killclient,

# brightness
bind=none,XF86MonBrightnessup,spawn,brightnessctl s +2%
bind=shift,XF86MonBrightnessup,spawn,brightnessctl s 100%
bind=none,XF86MonBrightnessdown,spawn,brightnessctl s 2%-
bind=shift,XF86MonBrightnessdown,spawn,brightnessctl s 1%

# volume
bind=none,XF86AudioRaiseVolume,spawn,wpctl set-volume @DEFAULT_SINK@ 5%+
bind=none,XF86AudioLowerVolume,spawn,wpctl set-volume @DEFAULT_SINK@ 5%-
bind=none,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_SINK@ toggle
bind=shift,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_SOURCE@ toggle

# switch window focus
bind=super,Tab,focusstack,next
bind=super,h,focusdir,left
bind=super,l,focusdir,right
bind=super,k,focusdir,up
bind=super,j,focusdir,down

# # swap window
# bind=super+shift,up,exchange_client,up
# bind=super+shift,down,exchange_client,down
# bind=super+shift,Left,exchange_client,left
# bind=super+shift,Right,exchange_client,right
bind=super,return,exchange_stack_client

# # switch window status
# bind=super,g,toggleglobal,
# bind=alt,Tab,toggleoverview,
# bind=alt,backslash,togglefloating,
# bind=super,a,togglemaximizescreen,
bind=super,f,togglefullscreen,
# bind=super,a,togglefakefullscreen,
# bind=super,i,minimized,
# bind=super,o,toggleoverlay,
# bind=super+shift,I,restore_minimized
# bind=alt,z,toggle_scratchpad

# # scroller layout
# bind=alt,e,set_proportion,1.0
# bind=alt,x,switch_proportion_preset,

# switch layout
# bind=super,n,switch_layout

# # tag switch
# bind=super,Left,viewtoleft,0
# bind=ctrl,Left,viewtoleft_have_client,0
# bind=super,Right,viewtoright,0
# bind=ctrl,Right,viewtoright_have_client,0
# bind=ctrl+super,Left,tagtoleft,0
# bind=ctrl+super,Right,tagtoright,0

bind=super,1,view,1,0
bind=super,2,view,2,0
bind=super,3,view,3,0
bind=super,4,view,4,0
bind=super,5,view,5,0
bind=super,6,view,6,0
bind=super,7,view,7,0
bind=super,8,view,8,0
bind=super,9,view,9,0

# tag: move client to the tag and focus it
# tagsilent: move client to the tag and not focus it
bind=super+shift,1,tag,1,0
bind=super+shift,2,tag,2,0
bind=super+shift,3,tag,3,0
bind=super+shift,4,tag,4,0
bind=super+shift,5,tag,5,0
bind=super+shift,6,tag,6,0
bind=super+shift,7,tag,7,0
bind=super+shift,8,tag,8,0
bind=super+shift,9,tag,9,0

# monitor switch
bind=super+shift,h,focusmon,left
bind=super+shift,l,focusmon,right
bind=super,return,tagmon,right

# # resizewin
# bind=ctrl+alt,up,resizewin,+0,-50
# bind=ctrl+alt,down,resizewin,+0,+50
# bind=ctrl+alt,Left,resizewin,-50,+0
# bind=ctrl+alt,Right,resizewin,+50,+0

# Mouse Button Bindings
# btn_left and btn_right can't bind none mod key
mousebind=super,btn_left,moveresize,curmove
mousebind=none,btn_middle,togglemaximizescreen,0
mousebind=super,btn_right,moveresize,curresize

# Axis Bindings
axisbind=super,up,viewtoleft_have_client
axisbind=super,down,viewtoright_have_client

# Script Bindings
bind=alt+shift,p,spawn,$HOME/.local/bin/pdf-search.sh
bind=alt+shift,b,spawn,$HOME/.local/bin/custom-scripts/bookmarks/bookmarks.sh
