# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x161616ff
bordercolor = 0x636363ff
focuscolor = 0x33b1ffff
maximizescreencolor = 0x42be65ff
urgentcolor = 0xee5396ff
scratchpadcolor = 0xbe95ffff
globalcolor = 0x004f80ff
overlaycolor = 0x0e3f1cff
