# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x1c1c24ff
rootcolor = 0x141415ff
bordercolor = 0x606079ff
focuscolor = 0x7e98e8ff
maximizescreencolor = 0x6e94b2ff
urgentcolor = 0xd8647eff
scratchpadcolor = 0xbb9dbdff
globalcolor = 0x0e33a6ff
overlaycolor = 0x1e3a50ff
